version: '3'
services:
  pubsub:
    image: google/cloud-sdk:latest
    command: [ "gcloud", "beta", "emulators", "pubsub", "start", "--host-port=0.0.0.0:8085", "--log-http", "--verbosity=debug", "--user-output-enabled" ]
    ports:
    - 8085:8085
